### ISSUE TITLE
Segfault while adding files

### ISSUE THREAD

**Issue by aladar42** [TheWiseNoob/OMP#8] opened 2018-02-19 14:03 UTC
I opened a new issue rather than have it in the new one, I hope that's okay with you.

Anyway, as I assume folder addition isn't supported yet (or at least I couldn't find a way), I tried to add an album track by track. Around about 4-5th track added OMP either locks up or crashes.

Here's the GDB output again:
https://pastebin.com/wuPFPYEQ

Arch Linux, kernel 4.15.3, gcc 7.3.0.

**Comment by aladar42** [comment] 2018-02-19 14:07
Okay, I tried a few more albums and it seems it's only happening with some, not all of them. Can't find anything that would be wrong with the ones that cause it, though.

**Comment by TheWiseNoob** [comment] 2018-02-20 01:26
Adding by folder is not supported yet, but it will be present by 0.2. What kind of audio file were you adding?

**Comment by aladar42** [comment] 2018-02-20 14:33
Just a regular 320 kbps MP3, nothing weird about it, all the other players handle it normally...

**Comment by TheWiseNoob** [comment] 2018-02-20 17:37
That's weird because mp3s have been working fine for me. I'll look into testing more of them. If any of those mp3s are damaged, it could be that. I need to fix a bug with damaged files. The program is still pre-alpha, so issues like this are expected.

**Comment by aladar42** [comment] 2018-02-20 18:26
I'm not sure how to check if it's damaged, but it plays just fine in LineageOS' default music player, VLC on Android, foobar2000 and Deadbeef on Linux, so I think it's fine. I would upload the file, but I assume that would consist a copyright violation.

> The program is still pre-alpha, so issues like this are expected.

That's why I'm reporting the bugs, trying to help out as best as I can. :)

**Comment by TheWiseNoob** [comment] 2018-02-20 18:58
Thanks. I really appreciate the help. If you want to email me a link to it on your Google Drive, Dropbox, or anything similar, my gmail email account is the same as my username here. I will definitely test it myself if you send a file you've confirmed as problematic.

**Comment by aladar42** [comment] 2018-02-24 19:57
I can't find your email. :)

**Comment by TheWiseNoob** [comment] 2018-03-01 02:45
I've fixed the bug that causes the second file you sent me to crash OMP when it failed to read the file properly. I need to fix another bug that is causing that file to not be read properly. The first file, Build by Cubanate, is playing fine for me. Was it crashing OMP for you? 

I'll be working on this more tomorrow.

**Comment by aladar42** [comment] 2018-03-01 20:25
Oh, I sent you a wrong file, it was supposed to be track 6, not 4. :) I assume that the bug is the same though, so I'll just try again in 0.0.7. Thanks. :)

**Comment by TheWiseNoob** [comment] 2018-03-02 04:11
I'm pretty sure I've solved the problem. The problematic file you sent me opens properly for me now and plays. I'll keep this Issue open until you have a chance to test the fix on more of your collection. This will be included in the 0.0.7 update that will be released sometime on March 18th, 2018.

Thanks for the helpful bug report!

**Comment by aladar42** [comment] 2018-03-02 21:05
No problem, happy to help. I'll let you know when the update lands. :)

**Comment by TheWiseNoob** [comment] 2018-03-18 22:09
Let me know if today's update fixed this problem or not!

**Comment by aladar42** [comment] 2018-03-20 15:36
Hey, thanks, the files in questions aren't crashing anymore. :) I'll close this issue and let you know if I ever find something else.

**Closed** 2018-03-20 15:37 UTC

**Comment by TheWiseNoob** [comment] 2018-03-20 18:35
Thanks for testing it for me!
